services:
  postgres:
    ports:
      - 5432:5432

  jupyter:
    image: cube-in-a-box-jupyter:dev
    pull_policy: never

  jupyterhub:
    environment:
      - DOCKER_JUPYTER_IMAGE=cube-in-a-box-jupyter:dev

  explorer:
    image: cube-in-a-box-explorer:dev
    pull_policy: never