services:
  postgres:
    image: kartoza/postgis:17-3.5  # 16-3.4  # 13-3.1
    environment:
      - POSTGRES_DB=opendatacube
      - POSTGRES_PASSWORD=opendatacubepassword
      - POSTGRES_USER=opendatacube
    volumes:
      - ./data/pg:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always

  jupyter:
    build: .
    environment:
      - ODC_DEFAULT_DB_HOSTNAME=postgres
      - ODC_DEFAULT_DB_USERNAME=opendatacube
      - ODC_DEFAULT_DB_PASSWORD=opendatacubepassword
      - ODC_DEFAULT_DB_DATABASE=opendatacube
      # - DB_HOSTNAME=postgres
      # - DB_USERNAME=opendatacube
      # - DB_PASSWORD=opendatacubepassword
      # - DB_DATABASE=opendatacube
      - AWS_NO_SIGN_REQUEST=true
      - STAC_API_URL=https://explorer.sandbox.dea.ga.gov.au/stac/
      # - CIABPASSWORD=${CIABPASSWORD:-secretpassword}
    links:
      - postgres:postgres
    ports:
      - "80:8888"
      - "8787:8787"
    volumes:
      - ./notebooks:/notebooks
      - ./tests:/tests
      - ./products:/products
      # - ./products.csv:/products.csv
      # - ./lsX_c2l2_sp.products.yaml:/lsX_c2l2_sp.products.yaml
      # - ./io_lulc_annual_v02.product.yaml:/io_lulc_annual_v02.product.yaml
    restart: always
  checkdb:
    image: schaffdev/port_check:latest
    environment:
      - CHECK_HOST=postgres
      - CHECK_PORT=5432
    links:
      - postgres:postgres

  explorer:
    # image: opendatacube/explorer
    build:
      context: datacube-explorer
      dockerfile: Dockerfile
    environment:
      - DB_HOSTNAME=postgres
      - DB_USERNAME=opendatacube
      - DB_PASSWORD=opendatacubepassword
      - DB_DATABASE=opendatacube
      - DB_PORT=5432
      - FLASK_ENV=development
      - FLASK_APP=cubedash
      - FLASK_DEBUG=1
      - CUBEDASH_DEFAULT_TIMEZONE=Europe/Zurich
    ports:
      - "81:8080"
      - "8090:8090"
    depends_on:
      - postgres

  # ows:
  #   # image: opendatacube/ows
  #   build:
  #     context: datacube-ows
  #     dockerfile: Dockerfile
  #   volumes:
  #     - ./datacube-ows/ows_config:/env/config/ows_config
  #     - ./datacube.conf:/env/config/datacube.conf
  #   environment:
  #     # - POSTGRES_DB=opendatacube
  #     # - POSTGRES_PASSWORD=opendatacubepassword
  #     # - POSTGRES_USER=opendatacube
  #     # - POSTGRES_HOST=postgres
  #     # - POSTGRES_PORT=5432
  #     - ODC_CONFIG_PATH=/env/config/datacube.conf
  #     - ODC_DEFAULT_DB_URL=postgresql://opendatacube:opendatacubepassword@postgres:5432/opendatacube
  #     - ODC_OWSPOSTGIS_DB_URL=postgresql://opendatacubeusername:opendatacubepassword@postgres:5432/odc_postgis
  #     - ODC_DEFAULT_INDEX_DRIVER=postgis
  #     - PYTHONPATH=/env/config
  #     - DATACUBE_OWS_CFG=ows_config.pacific_ows.ows_cfg
  #     - OWS_CFG_DIR=/env/config/ows_config
  #   ports:
  #     - "8000:8000"
  #   depends_on:
  #     - postgres
