#!/usr/bin/env python3
"""
scripts/index_aef.py

Index AlphaEarth Foundations (AEF) annual satellite embeddings — mirrored as
Cloud-Optimized GeoTIFFs on AWS S3 via Source Cooperative (source.coop/tge-labs/aef)
— into an Open Data Cube instance.

Pipeline:
    1. Query AlphaEarth using aef-loader (AEFIndex), filtered by bbox + year(s).
    2. Load band count / dtype / nodata from the product registered in the ODC
       index (the product added via `datacube product add`), and calibrate pixel
       resolution from a single COG header (one network read per run).
    3. Derive each tile's GeoTIFF grid metadata (crs, transform, shape) purely
       from the aef-loader parquet index — no per-tile COG open.
    4. Generate one EO3 dataset YAML document per tile (parallel across threads).
    5. Add the generated documents to the datacube with `datacube dataset add`.

Prerequisites:
    pip install aef-loader
    datacube product add config/products/aef/aef_annual.odc-product.yaml

Usage:
    python3 scripts/index_aef.py \\
        --bbox 5.95,45.81,10.50,47.81 \\
        --years 2022 \\
        --product aef_annual \\
        --docs-dir dataset_docs/aef

    # Range of years, capped for a quick test, no indexing:
    python3 scripts/index_aef.py --bbox 5.95,45.81,10.50,47.81 \\
        --years 2020-2023 --limit 5 --dry-run

    # Skip the one-shot COG header read (e.g. offline) by passing the resolution:
    python3 scripts/index_aef.py --bbox 5.95,45.81,10.50,47.81 \\
        --years 2022 --resolution 10

Network:
    The aef-loader parquet index is fetched (cached after the first run) from
    the public, unsigned S3 bucket us-west-2.opendata.source.coop via
    aef-loader/obstore with AWS_NO_SIGN_REQUEST set automatically. Band count,
    dtype and nodata are read from the product registered in the ODC index (not
    the YAML on disk). One COG header is read per run to calibrate pixel
    resolution (overridable with --resolution). No other per-tile COG reads are
    performed — grid metadata comes from the index, so indexation is local
    CPU/disk I/O after the index download and the single calibration read.
"""

from __future__ import annotations

import argparse
import asyncio
import logging
import math
import subprocess
import sys
import uuid
from concurrent.futures import ThreadPoolExecutor
from pathlib import Path
from typing import Union

import rasterio
import yaml
from rasterio.errors import RasterioIOError

import datacube
from aef_loader import AEFIndex, DataSource

logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)s %(message)s")
log = logging.getLogger("index_aef")

# Deterministic UUID namespace for datasets generated by this script.
AEF_UUID_NAMESPACE = uuid.uuid5(uuid.NAMESPACE_URL, "https://source.coop/tge-labs/aef")

# AEF grid metadata is sourced at runtime, not hardcoded:
#   - band count (N_BANDS), dtype and nodata come from the product description
#     as registered in the ODC index (the product added via
#     `datacube product add`) — see load_product_meta(). Using the registered
#     product (rather than the YAML on disk) avoids cwd/path issues inside the
#     container and is the authoritative source actually used by dc.load().
#   - resolution (m/px) is calibrated from a single COG header per run
#     (see calibrate_resolution()); it is uniform across the v1/annual dataset
#     (every tile spans 81920 m → 8192 px at 10 m), so one read calibrates all.
# This keeps indexation network-free per tile: 1 calibration read total, then
# every grid is derived from the parquet index's utm_bounds.

# GDAL config options for the one-shot COG header read used to calibrate
# resolution. Not used per tile.
AEF_GDAL_ENV = {
    "GDAL_DISABLE_READDIR_ON_OPEN": "YES",
    "CPL_VSIL_CURL_ALLOWED_EXTENSIONS": ".tif,.tiff",
}

# The public Source Cooperative bucket, addressed as a plain HTTPS URL rather
# than s3://. This is deliberate: GDAL's /vsis3/ driver reads
# AWS_S3_ENDPOINT / AWS_ACCESS_KEY_ID / AWS_SECRET_ACCESS_KEY from the
# process environment - and the jupyter/JupyterHub containers set those
# globally for CDSE-authenticated products. Any dataset indexed with an
# s3:// path will fail in *every* user's dc.load(), not just this script,
# because there's no reliable way to scope AWS env vars per-dataset at read
# time. Using a plain https:// href instead makes GDAL fall back to
# /vsicurl/ - an ordinary anonymous HTTPS GET with range-request support for
# COGs - which never touches AWS config at all, so it's unaffected by
# whatever CDSE settings are active in a given container.
SOURCE_COOP_S3_PREFIX = "s3://us-west-2.opendata.source.coop/"
SOURCE_COOP_HTTPS_PREFIX = "https://s3.us-west-2.amazonaws.com/us-west-2.opendata.source.coop/"


def to_https_href(tile_path: str) -> str:
    """Convert an aef-loader s3:// tile path into a plain HTTPS URL."""
    if tile_path.startswith(SOURCE_COOP_S3_PREFIX):
        return SOURCE_COOP_HTTPS_PREFIX + tile_path[len(SOURCE_COOP_S3_PREFIX):]
    return tile_path


def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
    )
    p.add_argument(
        "--bbox",
        required=True,
        help="minx,miny,maxx,maxy in WGS84, e.g. 5.95,45.81,10.50,47.81",
    )
    year_group = p.add_mutually_exclusive_group(required=True)
    year_group.add_argument(
        "--years", help="Single year (2022) or range (2020-2023)"
    )
    year_group.add_argument(
        "--datetime",
        help="ISO8601 start/end range, e.g. 2021-01-01/2021-12-31 "
        "(matches the DATETIME convention used elsewhere in this repo; "
        "only the year of each side is used, since AEF is annual data)",
    )
    p.add_argument(
        "--product",
        default="aef_annual",
        help="ODC product name to register datasets against (must already exist "
        "via `datacube product add`)",
    )
    p.add_argument(
        "--docs-dir",
        default="dataset_docs/aef",
        help="Directory to write generated EO3 YAML documents to",
    )
    p.add_argument(
        "--limit",
        type=int,
        default=None,
        help="Optional cap on the number of tiles processed (useful for testing)",
    )
    p.add_argument(
        "--dry-run",
        action="store_true",
        help="Generate EO3 documents but do not run `datacube dataset add`",
    )
    p.add_argument(
        "--workers",
        type=int,
        default=16,
        help="Number of worker threads for building/writing EO3 documents "
        "(grid metadata is derived locally, so this is pure CPU/disk I/O)",
    )
    p.add_argument(
        "--resolution",
        type=float,
        default=None,
        help="Override pixel resolution in metres/px, skipping the one-shot "
        "COG header calibration read (useful offline or to force a value)",
    )
    return p.parse_args()


def parse_years(years: str) -> Union[int, tuple]:
    if "-" in years:
        start, end = years.split("-", 1)
        return int(start), int(end)
    return int(years)


def parse_datetime_range(datetime_range: str) -> Union[int, tuple]:
    """Take a repo-standard 'start/end' ISO8601 range (e.g. from $DATETIME)
    and reduce it to the year(s) aef-loader's query() expects."""
    start, _, end = datetime_range.partition("/")
    start_year = int(start[:4])
    end_year = int(end[:4]) if end else start_year
    if start_year == end_year:
        return start_year
    return start_year, end_year


def tile_uuid(tile_path: str) -> str:
    """Deterministic dataset UUID derived from the tile's storage path."""
    return str(uuid.uuid5(AEF_UUID_NAMESPACE, tile_path))


def band_name(i: int) -> str:
    return f"A{i:02d}"


def load_product_meta(product_name: str) -> dict:
    """Read band count, dtype and nodata from the product registered in the
    Open Data Cube index.

    The product must already be added via `datacube product add` (which `make
    product` does before `make index`). Reading the registered product — rather
    than the YAML on disk — is authoritative (it is exactly what dc.load() uses)
    and avoids depending on the YAML file being reachable from the script's
    working directory inside the container. Measurement dtype/nodata are
    uniform across the AEF product, so the first measurement's values are used.
    """
    dc = datacube.Datacube(app="index_aef")
    try:
        product = dc.index.products.get_by_name(product_name)
    finally:
        dc.close()
    if product is None:
        raise RuntimeError(
            f"Product {product_name!r} not found in the datacube index; "
            "run `datacube product add` first."
        )
    measurements = product.measurements  # Mapping[str, Measurement]
    first = next(iter(measurements.values()))
    return {
        "n_bands": len(measurements),
        "dtype": first["dtype"],
        "nodata": first["nodata"],
    }


def calibrate_resolution(tiles, override: float | None) -> float:
    """Determine pixel resolution (m/px) from one COG header, or an override.

    Resolution is uniform across the v1/annual dataset, so a single header read
    (range request for the TIFF tags) calibrates every tile. Falls back to the
    next tile if the first header read fails; raises if none can be read and no
    override was supplied.
    """
    if override is not None:
        log.info("Using --resolution=%s m/px (skipping COG header read)", override)
        return float(override)
    for tile in tiles:
        try:
            with rasterio.Env(**AEF_GDAL_ENV), rasterio.open(
                to_https_href(tile.path)
            ) as src:
                xres, yres = src.res
                if not math.isclose(xres, yres, rel_tol=1e-6):
                    log.warning(
                        "%s has non-square pixels (x=%s y=%s); using x",
                        tile.path,
                        xres,
                        yres,
                    )
                log.info(
                    "Calibrated resolution from %s: %s m/px", tile.path, xres
                )
                return float(xres)
        except RasterioIOError as exc:
            log.warning("Calibration read failed for %s: %s", tile.path, exc)
    raise RuntimeError(
        "Could not calibrate resolution from any tile COG header; "
        "pass --resolution to set it explicitly."
    )


def derive_grid(tile, resolution_m: float, n_bands: int, dtype, nodata) -> dict:
    """Derive CRS / transform / shape / band count from the parquet index.

    The aef-loader index already carries each tile's native CRS (EPSG) and
    the UTM bounds of its raw pixel array, and the v1/annual dataset is
    uniformly 10 m with 64 int8 bands. The EO3 grid is therefore fully
    determined without opening the COG over HTTPS — this removes a serial
    network round-trip per tile, which was the dominant indexation cost.
    """
    west, south, east, north = tile.utm_bounds
    width = round((east - west) / resolution_m)
    height = round((north - south) / resolution_m)
    crs = f"EPSG:{tile.crs_epsg}"
    return {
        "crs": crs,
        "transform": [resolution_m, 0.0, west, 0.0, -resolution_m, north],
        "shape": [height, width],
        "count": n_bands,
        "dtype": dtype,
        "nodata": nodata,
    }


def build_eo3_document(tile, grid: dict, product: str, n_bands: int) -> dict:
    """Build an EO3 dataset document dict for a single AEF tile."""
    href = to_https_href(tile.path)
    n_bands = min(grid["count"], n_bands)
    measurements = {
        band_name(i): {"path": href, "band": i + 1} for i in range(n_bands)
    }

    year = tile.year
    region_code = f"{tile.utm_zone or grid['crs'].replace(':', '_')}"

    return {
        "$schema": "https://schemas.opendatacube.org/dataset",
        "id": tile_uuid(tile.path),
        "product": {"name": product},
        "crs": grid["crs"],
        "grids": {
            "default": {
                "shape": grid["shape"],
                "transform": grid["transform"],
            }
        },
        "measurements": measurements,
        "properties": {
            "datetime": f"{year}-07-02T00:00:00Z",
            "dtr:start_datetime": f"{year}-01-01T00:00:00Z",
            "dtr:end_datetime": f"{year}-12-31T23:59:59Z",
            "odc:file_format": "GeoTIFF",
            "odc:producer": "google.com",
            "odc:product_family": "satellite_embedding",
            "odc:region_code": region_code,
        },
        "lineage": {},
    }


async def query_tiles(bbox: tuple, years, limit):
    index = AEFIndex(source=DataSource.SOURCE_COOP)
    await index.download()
    index.load()
    return await index.query(bbox=bbox, years=years, limit=limit)


def write_doc(doc: dict, docs_dir: Path) -> Path:
    out_path = docs_dir / f"{doc['id']}.odc-metadata.yaml"
    with out_path.open("w") as f:
        yaml.safe_dump(doc, f, sort_keys=False)
    return out_path


def add_to_datacube(doc_paths: list) -> None:
    if not doc_paths:
        log.info("No documents to add.")
        return
    cmd = ["datacube", "dataset", "add", *[str(p) for p in doc_paths]]
    log.info("Running `datacube dataset add` for %d document(s)", len(doc_paths))
    subprocess.run(cmd, check=True)


def process_tile(
    tile, product: str, docs_dir: Path, resolution_m: float, meta: dict
) -> Path | None:
    """Derive grid, build the EO3 doc, and write it to disk for one tile."""
    try:
        grid = derive_grid(
            tile, resolution_m, meta["n_bands"], meta["dtype"], meta["nodata"]
        )
    except (KeyError, TypeError, ValueError) as exc:
        log.error("Could not derive grid for %s: %s", tile.path, exc)
        return None
    doc = build_eo3_document(tile, grid, product, meta["n_bands"])
    return write_doc(doc, docs_dir)


def main() -> int:
    args = parse_args()
    bbox = tuple(float(v) for v in args.bbox.split(","))
    years = (
        parse_datetime_range(args.datetime) if args.datetime else parse_years(args.years)
    )
    docs_dir = Path(args.docs_dir)
    docs_dir.mkdir(parents=True, exist_ok=True)

    log.info("Querying AEF index (Source Cooperative): bbox=%s years=%s", bbox, years)
    tiles = asyncio.run(query_tiles(bbox, years, args.limit))
    log.info("Matched %d tile(s)", len(tiles))

    if not tiles:
        log.warning("No AEF tiles matched the given bbox/years.")
        return 0

    meta = load_product_meta(args.product)
    log.info(
        "Product %s: %d band(s), dtype=%s, nodata=%s",
        args.product,
        meta["n_bands"],
        meta["dtype"],
        meta["nodata"],
    )
    resolution_m = calibrate_resolution(tiles, args.resolution)

    # Grid metadata is derived locally (no per-tile network), so building and
    # writing EO3 documents is pure CPU/disk I/O — parallelize across threads.
    workers = max(1, args.workers)
    doc_paths: list[Path] = []
    if workers == 1 or len(tiles) == 1:
        for tile in tiles:
            path = process_tile(
                tile, args.product, docs_dir, resolution_m, meta
            )
            if path is not None:
                doc_paths.append(path)
    else:
        with ThreadPoolExecutor(max_workers=workers) as pool:
            futures = [
                pool.submit(
                    process_tile, tile, args.product, docs_dir, resolution_m, meta
                )
                for tile in tiles
            ]
            for fut in futures:
                path = fut.result()
                if path is not None:
                    doc_paths.append(path)

    log.info("Generated %d EO3 document(s) in %s", len(doc_paths), docs_dir)

    if args.dry_run:
        log.info("--dry-run set: skipping `datacube dataset add`")
        return 0

    add_to_datacube(doc_paths)
    return 0


if __name__ == "__main__":
    sys.exit(main())
