#!/usr/bin/env python3
"""
scripts/index_aef.py

Index AlphaEarth Foundations (AEF) annual satellite embeddings — mirrored as
Cloud-Optimized GeoTIFFs on AWS S3 via Source Cooperative (source.coop/tge-labs/aef)
— into an Open Data Cube instance.

Pipeline:
    1. Query AlphaEarth using aef-loader (AEFIndex), filtered by bbox + year(s).
    2. Read exact GeoTIFF grid metadata (crs, transform, shape, band count) for
       each matching tile directly with rasterio.
    3. Generate one EO3 dataset YAML document per tile.
    4. Add the generated documents to the datacube with `datacube dataset add`.

Prerequisites:
    pip install aef-loader
    datacube product add config/products/source_coop/aef_annual.odc-product.yaml

Usage:
    python3 scripts/index_aef.py \\
        --bbox 5.95,45.81,10.50,47.81 \\
        --years 2022 \\
        --product aef_annual \\
        --docs-dir dataset_docs/aef

    # Range of years, capped for a quick test, no indexing:
    python3 scripts/index_aef.py --bbox 5.95,45.81,10.50,47.81 \\
        --years 2020-2023 --limit 5 --dry-run

Network:
    Reads the public, unsigned S3 bucket us-west-2.opendata.source.coop. No
    credentials are required; AWS_NO_SIGN_REQUEST is set automatically for
    both the index download (via aef-loader/obstore) and the per-tile
    rasterio/GDAL reads.
"""

from __future__ import annotations

import argparse
import asyncio
import logging
import subprocess
import sys
import uuid
from pathlib import Path
from typing import Union

import rasterio
import yaml
from rasterio.errors import RasterioIOError

from aef_loader import AEFIndex, DataSource

logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)s %(message)s")
log = logging.getLogger("index_aef")

# Deterministic UUID namespace for datasets generated by this script.
AEF_UUID_NAMESPACE = uuid.uuid5(uuid.NAMESPACE_URL, "https://source.coop/tge-labs/aef")

# AEF embeddings have 64 bands: A00 .. A63.
N_BANDS = 64

# The public Source Cooperative bucket, addressed as a plain HTTPS URL rather
# than s3://. This is deliberate: GDAL's /vsis3/ driver reads
# AWS_S3_ENDPOINT / AWS_ACCESS_KEY_ID / AWS_SECRET_ACCESS_KEY from the
# process environment - and the jupyter/JupyterHub containers set those
# globally for CDSE-authenticated products. Any dataset indexed with an
# s3:// path will fail in *every* user's dc.load(), not just this script,
# because there's no reliable way to scope AWS env vars per-dataset at read
# time. Using a plain https:// href instead makes GDAL fall back to
# /vsicurl/ - an ordinary anonymous HTTPS GET with range-request support for
# COGs - which never touches AWS config at all, so it's unaffected by
# whatever CDSE settings are active in a given container.
SOURCE_COOP_S3_PREFIX = "s3://us-west-2.opendata.source.coop/"
SOURCE_COOP_HTTPS_PREFIX = "https://s3.us-west-2.amazonaws.com/us-west-2.opendata.source.coop/"

# GDAL config options for reading COGs efficiently over plain HTTPS.
AEF_GDAL_ENV = {
    "GDAL_DISABLE_READDIR_ON_OPEN": "YES",
    "CPL_VSIL_CURL_ALLOWED_EXTENSIONS": ".tif,.tiff",
}


def to_https_href(tile_path: str) -> str:
    """Convert an aef-loader s3:// tile path into a plain HTTPS URL."""
    if tile_path.startswith(SOURCE_COOP_S3_PREFIX):
        return SOURCE_COOP_HTTPS_PREFIX + tile_path[len(SOURCE_COOP_S3_PREFIX):]
    return tile_path


def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
    )
    p.add_argument(
        "--bbox",
        required=True,
        help="minx,miny,maxx,maxy in WGS84, e.g. 5.95,45.81,10.50,47.81",
    )
    year_group = p.add_mutually_exclusive_group(required=True)
    year_group.add_argument(
        "--years", help="Single year (2022) or range (2020-2023)"
    )
    year_group.add_argument(
        "--datetime",
        help="ISO8601 start/end range, e.g. 2021-01-01/2021-12-31 "
        "(matches the DATETIME convention used elsewhere in this repo; "
        "only the year of each side is used, since AEF is annual data)",
    )
    p.add_argument(
        "--product",
        default="aef_annual",
        help="ODC product name to register datasets against (must already exist "
        "via `datacube product add`)",
    )
    p.add_argument(
        "--docs-dir",
        default="dataset_docs/aef",
        help="Directory to write generated EO3 YAML documents to",
    )
    p.add_argument(
        "--limit",
        type=int,
        default=None,
        help="Optional cap on the number of tiles processed (useful for testing)",
    )
    p.add_argument(
        "--dry-run",
        action="store_true",
        help="Generate EO3 documents but do not run `datacube dataset add`",
    )
    return p.parse_args()


def parse_years(years: str) -> Union[int, tuple]:
    if "-" in years:
        start, end = years.split("-", 1)
        return int(start), int(end)
    return int(years)


def parse_datetime_range(datetime_range: str) -> Union[int, tuple]:
    """Take a repo-standard 'start/end' ISO8601 range (e.g. from $DATETIME)
    and reduce it to the year(s) aef-loader's query() expects."""
    start, _, end = datetime_range.partition("/")
    start_year = int(start[:4])
    end_year = int(end[:4]) if end else start_year
    if start_year == end_year:
        return start_year
    return start_year, end_year


def tile_uuid(tile_path: str) -> str:
    """Deterministic dataset UUID derived from the tile's storage path."""
    return str(uuid.uuid5(AEF_UUID_NAMESPACE, tile_path))


def band_name(i: int) -> str:
    return f"A{i:02d}"


def read_grid_metadata(tile_href: str) -> dict:
    """Read CRS / transform / shape / band count directly from the COG with rasterio."""
    with rasterio.Env(**AEF_GDAL_ENV):
        with rasterio.open(tile_href) as src:
            if src.count < N_BANDS:
                log.warning(
                    "%s has %d bands, expected %d - indexing what's present",
                    tile_href,
                    src.count,
                    N_BANDS,
                )
            return {
                "crs": f"EPSG:{src.crs.to_epsg()}",
                "transform": list(src.transform)[:6],
                "shape": [src.height, src.width],
                "count": src.count,
                "dtype": src.dtypes[0],
                "nodata": src.nodata,
            }


def build_eo3_document(tile, grid: dict, product: str) -> dict:
    """Build an EO3 dataset document dict for a single AEF tile."""
    href = to_https_href(tile.path)
    n_bands = min(grid["count"], N_BANDS)
    measurements = {
        band_name(i): {"path": href, "band": i + 1} for i in range(n_bands)
    }

    year = tile.year
    region_code = f"{tile.utm_zone or grid['crs'].replace(':', '_')}-{tile.id}"

    return {
        "$schema": "https://schemas.opendatacube.org/dataset",
        "id": tile_uuid(tile.path),
        "product": {"name": product},
        "crs": grid["crs"],
        "grids": {
            "default": {
                "shape": grid["shape"],
                "transform": grid["transform"],
            }
        },
        "measurements": measurements,
        "properties": {
            "datetime": f"{year}-07-02T00:00:00Z",
            "dtr:start_datetime": f"{year}-01-01T00:00:00Z",
            "dtr:end_datetime": f"{year}-12-31T23:59:59Z",
            "odc:file_format": "GeoTIFF",
            "odc:producer": "google.com",
            "odc:product_family": "satellite_embedding",
            "odc:region_code": region_code,
        },
        "lineage": {},
    }


async def query_tiles(bbox: tuple, years, limit):
    index = AEFIndex(source=DataSource.SOURCE_COOP)
    await index.download()
    index.load()
    return await index.query(bbox=bbox, years=years, limit=limit)


def write_doc(doc: dict, docs_dir: Path) -> Path:
    out_path = docs_dir / f"{doc['id']}.odc-metadata.yaml"
    with out_path.open("w") as f:
        yaml.safe_dump(doc, f, sort_keys=False)
    return out_path


def add_to_datacube(doc_paths: list) -> None:
    if not doc_paths:
        log.info("No documents to add.")
        return
    cmd = ["datacube", "dataset", "add", *[str(p) for p in doc_paths]]
    log.info("Running `datacube dataset add` for %d document(s)", len(doc_paths))
    subprocess.run(cmd, check=True)


def main() -> int:
    args = parse_args()
    bbox = tuple(float(v) for v in args.bbox.split(","))
    years = (
        parse_datetime_range(args.datetime) if args.datetime else parse_years(args.years)
    )
    docs_dir = Path(args.docs_dir)
    docs_dir.mkdir(parents=True, exist_ok=True)

    log.info("Querying AEF index (Source Cooperative): bbox=%s years=%s", bbox, years)
    tiles = asyncio.run(query_tiles(bbox, years, args.limit))
    log.info("Matched %d tile(s)", len(tiles))

    if not tiles:
        log.warning("No AEF tiles matched the given bbox/years.")
        return 0

    doc_paths = []
    for tile in tiles:
        try:
            grid = read_grid_metadata(to_https_href(tile.path))
        except RasterioIOError as exc:
            log.error("Could not read %s: %s", tile.path, exc)
            continue
        doc = build_eo3_document(tile, grid, args.product)
        doc_paths.append(write_doc(doc, docs_dir))

    log.info("Generated %d EO3 document(s) in %s", len(doc_paths), docs_dir)

    if args.dry_run:
        log.info("--dry-run set: skipping `datacube dataset add`")
        return 0

    add_to_datacube(doc_paths)
    return 0


if __name__ == "__main__":
    sys.exit(main())
